services:
  app:
    build: .
    container_name: finder-ai-container
    volumes:
      - ./:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    device_requests:
      - driver: nvidia
        count: all
        capabilities: [gpu]
    command: ["sleep", "infinity"]
    user: "${UID}:${GID}"
